# Generated by Django 5.1.1 on 2024-09-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="is_published",
            new_name="published",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
